spring.datasource.url=mysql://b6bf7e7d2e6e54:96742534@us-cdbr-iron-east-02.cleardb.net/heroku_02dd00e851c988a?reconnect=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false